//
//  AppIconGenerator.swift
//  Kestrel
//
//  SwiftUI version of the app icon for previews and ImageRenderer export.
//  The canonical icon is generated by generate_icon.swift at the project root.
//

import SwiftUI

// MARK: - App Icon View

struct KestrelAppIconView: View {
    let size: CGFloat

    var body: some View {
        ZStack {
            Color(red: 0.031, green: 0.047, blue: 0.078)

            RadialGradient(
                colors: [
                    Color(red: 0.0, green: 1.0, blue: 0.612).opacity(0.18),
                    Color(red: 0.0, green: 0.5, blue: 0.3).opacity(0.04),
                    Color.clear
                ],
                center: .center,
                startRadius: 0,
                endRadius: size * 0.42
            )

            KestrelBirdShape()
                .fill(Color(red: 0.0, green: 1.0, blue: 0.612))
                .frame(width: size * 0.92, height: size * 0.56)
                .offset(y: size * 0.04)

            ScanlineOverlay()
                .opacity(0.03)

        }
        .frame(width: size, height: size)
        .clipped()
    }
}

// MARK: - Kestrel Bird Shape

struct KestrelBirdShape: Shape {
    func path(in rect: CGRect) -> Path {
        let w = rect.width
        let h = rect.height
        var p = Path()

        func pt(_ x: CGFloat, _ y: CGFloat) -> CGPoint {
            CGPoint(x: w * x, y: h * y)
        }

        // Head top
        p.move(to: pt(0.488, 0.14))
        p.addCurve(to: pt(0.520, 0.23), control1: pt(0.510, 0.14), control2: pt(0.520, 0.19))

        // Right shoulder
        p.addCurve(to: pt(0.555, 0.25), control1: pt(0.528, 0.24), control2: pt(0.540, 0.25))

        // Right wing
        p.addCurve(to: pt(0.720, 0.13), control1: pt(0.610, 0.23), control2: pt(0.670, 0.17))
        p.addCurve(to: pt(0.870, 0.06), control1: pt(0.770, 0.10), control2: pt(0.825, 0.07))
        p.addCurve(to: pt(0.950, 0.09), control1: pt(0.910, 0.05), control2: pt(0.938, 0.065))

        // Right wing trailing
        p.addCurve(to: pt(0.830, 0.20), control1: pt(0.945, 0.12), control2: pt(0.895, 0.17))
        p.addCurve(to: pt(0.680, 0.30), control1: pt(0.770, 0.24), control2: pt(0.725, 0.27))
        p.addCurve(to: pt(0.575, 0.38), control1: pt(0.640, 0.33), control2: pt(0.605, 0.36))

        // Right flank
        p.addCurve(to: pt(0.548, 0.52), control1: pt(0.558, 0.42), control2: pt(0.552, 0.47))

        // Right tail
        p.addCurve(to: pt(0.565, 0.72), control1: pt(0.545, 0.59), control2: pt(0.555, 0.67))
        p.addLine(to: pt(0.560, 0.78))
        p.addLine(to: pt(0.540, 0.80))
        p.addLine(to: pt(0.515, 0.82))
        p.addLine(to: pt(0.500, 0.81))
        p.addLine(to: pt(0.485, 0.82))
        p.addLine(to: pt(0.460, 0.80))
        p.addLine(to: pt(0.440, 0.78))
        p.addLine(to: pt(0.435, 0.72))

        // Left tail up
        p.addCurve(to: pt(0.452, 0.52), control1: pt(0.445, 0.67), control2: pt(0.448, 0.59))
        p.addCurve(to: pt(0.425, 0.38), control1: pt(0.448, 0.47), control2: pt(0.442, 0.42))

        // Left wing trailing
        p.addCurve(to: pt(0.320, 0.30), control1: pt(0.395, 0.36), control2: pt(0.360, 0.33))
        p.addCurve(to: pt(0.170, 0.20), control1: pt(0.275, 0.27), control2: pt(0.230, 0.24))
        p.addCurve(to: pt(0.050, 0.09), control1: pt(0.105, 0.17), control2: pt(0.055, 0.12))

        // Left wingtip
        p.addCurve(to: pt(0.130, 0.06), control1: pt(0.062, 0.065), control2: pt(0.090, 0.05))

        // Left wing leading
        p.addCurve(to: pt(0.280, 0.13), control1: pt(0.175, 0.07), control2: pt(0.230, 0.10))
        p.addCurve(to: pt(0.445, 0.25), control1: pt(0.330, 0.17), control2: pt(0.390, 0.23))

        // Left shoulder to head
        p.addCurve(to: pt(0.480, 0.23), control1: pt(0.460, 0.25), control2: pt(0.472, 0.24))
        p.addCurve(to: pt(0.488, 0.14), control1: pt(0.480, 0.19), control2: pt(0.478, 0.14))

        p.closeSubpath()
        return p
    }
}

// MARK: - Scanline Overlay

struct ScanlineOverlay: View {
    var body: some View {
        Canvas { context, size in
            var y: CGFloat = 0
            while y < size.height {
                context.fill(Path(CGRect(x: 0, y: y, width: size.width, height: 1)), with: .color(.white))
                y += 3
            }
        }
    }
}

// MARK: - Icon Export

@MainActor
enum AppIconGenerator {
    @discardableResult
    static func exportIcon() -> UIImage? {
        let size: CGFloat = 1024
        let renderer = ImageRenderer(content: KestrelAppIconView(size: size))
        renderer.scale = 1.0
        renderer.proposedSize = .init(width: size, height: size)

        guard let uiImage = renderer.uiImage else { return nil }

        if let data = uiImage.pngData() {
            let path = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
                .appendingPathComponent("KestrelAppIcon.png")
            try? data.write(to: path)
        }
        return uiImage
    }
}

#Preview("App Icon") {
    KestrelAppIconView(size: 512)
        .clipShape(RoundedRectangle(cornerRadius: 512 * 0.2237))
        .padding(40)
        .background(Color.gray.opacity(0.2))
}
